services:
  server:
    build:
      context: .
      args:
        - BUILDPLATFORM:linux/arm64
      target: final
    environment:
      - ASPNETCORE_HTTPS_PORT=https://+:8081
      - ASPNETCORE_HTTP_PORT=http://+:8080
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/scripts/01-createDB.sql:/docker-entrypoint-initdb.d/01-createDB.sql
      - ./db/scripts/02-initDB.sql:/docker-entrypoint-initdb.d/02-initDB.sql
    environment:
      - POSTGRES_PASSWORD=PostgresPass
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
